<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/
$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)) :?>
    <?php foreach ($_attributes as $_attribute) : ?>
        <div class="select field configurable required">
            <label class="label" for="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()) ?></span>
            </label>

            <select name="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
                    data-selector="super_attribute[<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>]"
                    data-validate="{required:true}"
                    id="attribute<?= $block->escapeHtmlAttr($_attribute->getAttributeId()) ?>"
                    class="select__field select__field--super_attribute super-attribute-select">
                <option value=""><?= $block->escapeHtml(__('Choose an Option...')) ?></option>
            </select>

        </div>
    <?php endforeach; ?>
    <input type="hidden" id="stockstatus_url" name="stockstatus_url" value="<?php echo $block->getUrl('supplierinventory/inventorystatus/index')?>"/>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "configurable": {
                    "spConfig": <?= /* @noEscape */ $block->getJsonConfig() ?>,
                    "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar(
            'gallery_switch_strategy',
            'Magento_ConfigurableProduct'
        ) ?: 'replace'); ?>"
                }
            },
            "*" : {
                "Magento_ConfigurableProduct/js/catalog-add-to-cart": {}
            }
        }
    </script>
    <script type="text/javascript">
        require([
            "jquery",
            "jquery/ui"
        ], function (jQuery) {
            jQuery(document).ready(function(){
                jQuery(".super-attribute-select").change(function() {
                    setTimeout(function(){ updateCustomStock() }, 300);
                });
            });
            function updateCustomStock()
            {
                var productId=jQuery("input[name=selected_configurable_option]").val();
                jQuery.ajax({
                    url: jQuery('#stockstatus_url').val(),
                    type: 'post',
                    data: {product_id:productId},
                    success: function (data) {
                        if(data.success == 'true'){
                            jQuery('.custom__stock_status').html(data.response);
                        }
                    }
                });
            }
        });
    </script>

<?php endif;?>
